opam-version: "1"
name: "4.00.1+fpic"
src: "http://caml.inria.fr/pub/distrib/ocaml-4.00/ocaml-4.00.1.tar.gz"
build: [
  ["./configure" "-prefix" "%{prefix}%" "-cc" "gcc -fPIC" "-aspp" "gcc -c -fPIC"]
  ["%{make}%" "world"]
  ["%{make}%" "opt"]
  ["%{make}%" "opt.opt"]
  ["%{make}%" "install"]
]
packages: ["base-unix" "base-bigarray" "base-threads"]
env: [
  [CAML_LD_LIBRARY_PATH = "%{lib}%/stublibs"]
]
